export const cards = [
  {
    _id: '1',
    title: '33 слова о дизайне',
    duration: '1ч 47м',
    image: require('../images/movies/movie_1.jpg'),
  },
  {
    _id: '2',
    title: '33 слова о дизайне',
    duration: '1ч 47м',
    image: require('../images/movies/movie_2.jpg'),
  },
  {
    _id: '3',
    title: '33 слова о дизайне',
    duration: '1ч 47м',
    image: require('../images/movies/movie_3.jpg'),
  },
  {
    _id: '4',
    title: '33 слова о дизайне',
    duration: '1ч 47м',
    image: require('../images/movies/movie_4.jpg'),
  },
  {
    _id: '5',
    title: '33 слова о дизайне',
    duration: '1ч 47м',
    image: require('../images/movies/movie_5.jpg'),
  },
  {
    _id: '6',
    title: '33 слова о дизайне',
    duration: '1ч 47м',
    image: require('../images/movies/movie_6.jpg'),
  },
  {
    _id: '7',
    title: '33 слова о дизайне',
    duration: '1ч 47м',
    image: require('../images/movies/movie_7.jpg'),
  },
  {
    _id: '8',
    title: '33 слова о дизайне',
    duration: '1ч 47м',
    image: require('../images/movies/movie_8.jpg'),
  },
  {
    _id: '9',
    title: '33 слова о дизайне',
    duration: '1ч 47м',
    image: require('../images/movies/movie_9.jpg'),
  },
  {
    _id: '10',
    title: '33 слова о дизайне',
    duration: '1ч 47м',
    image: require('../images/movies/movie_10.jpg'),
  },
  {
    _id: '11',
    title: '33 слова о дизайне',
    duration: '1ч 47м',
    image: require('../images/movies/movie_11.jpg'),
  },
  {
    _id: '12',
    title: '33 слова о дизайне',
    duration: '1ч 47м',
    image: require('../images/movies/movie_12.jpg'),
  },
  {
    _id: '13',
    title: '33 слова о дизайне',
    duration: '1ч 47м',
    image: require('../images/movies/movie_13.jpg'),
  },
  {
    _id: '14',
    title: '33 слова о дизайне',
    duration: '1ч 47м',
    image: require('../images/movies/movie_14.jpg'),
  },
  {
    _id: '15',
    title: '33 слова о дизайне',
    duration: '1ч 47м',
    image: require('../images/movies/movie_15.jpg'),
  },
  {
    _id: '16',
    title: '33 слова о дизайне',
    duration: '1ч 47м',
    image: require('../images/movies/movie_16.jpg'),
  },
  {
    _id: '17',
    title: '33 слова о дизайне',
    duration: '1ч 47м',
    image: require('../images/movies/movie_17.jpg'),
  },
  {
    _id: '18',
    title: '33 слова о дизайне',
    duration: '1ч 47м',
    image: require('../images/movies/movie_18.jpg'),
  },
];
